### ISSUE TITLE
Get-RubrikFileset finds relics

### ISSUE THREAD

**Issue by aaronRubrik** [rubrikinc/rubrik-scripts-for-powershell#126]
**What happened**:
Get-RubrikFileset, when used to find a name, will return all filesets that were associated to that host, even relics.

**What you expected to happen**:
Ignore the relics and take the one actively assigned to the host

**How to reproduce it (as minimally and precisely as possible)**:
Chris Lumnah saw this with me on a WebEx. This can be reproduced by running this command on any host that has a fileset that's been relic'd.

**Anything else we need to know?**:

**Comment by JanosPesti** [comment]
I think there should be a -includeRelics option to specify if the relic filesets should be shown or not, as it could be useful to have the relics shown.

**Comment by clumnah** [comment]
The problem is actually not with the cmdlet. The cmdlet will show all filesets whether relic or not. The cmdlet has a way to filter out relics if you do not want to see them. 

In this case, the true problem is on the script New-FileSetSnapshot.ps1 where we do not have any filtering for relics when we make the call.
